/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import entidade.Plano;
import javax.swing.JOptionPane;

/**
 *
 * @author mathe_2led893
 */
public class InfoPlano extends javax.swing.JFrame {

    private Plano plano;

    public InfoPlano(Plano plano) {
        initComponents();
        this.plano = plano;
        lbNome.setText(plano.getTitular());
        lbPlano.setText(plano.getTipoPlano());

    }

    public InfoPlano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mostrar = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbPlano = new javax.swing.JLabel();
        varConsulta = new javax.swing.JButton();
        varExame = new javax.swing.JButton();
        varFatura = new javax.swing.JButton();
        varHistorico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        principal.setBackground(new java.awt.Color(204, 255, 204));

        mostrar.setColumns(20);
        mostrar.setRows(5);
        mostrar.setEnabled(false);
        jScrollPane2.setViewportView(mostrar);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informação plano");

        jLabel2.setText("Nome:");

        jLabel3.setText("Plano:");

        varConsulta.setBackground(new java.awt.Color(204, 255, 255));
        varConsulta.setText("consulta");
        varConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varConsultaActionPerformed(evt);
            }
        });

        varExame.setBackground(new java.awt.Color(204, 255, 255));
        varExame.setText("exame");
        varExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varExameActionPerformed(evt);
            }
        });

        varFatura.setBackground(new java.awt.Color(204, 255, 255));
        varFatura.setText("fatura");
        varFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varFaturaActionPerformed(evt);
            }
        });

        varHistorico.setBackground(new java.awt.Color(204, 255, 255));
        varHistorico.setText("histórico");
        varHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalLayout.createSequentialGroup()
                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPlano, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(lbNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(varHistorico)
                    .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(varFatura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(varExame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(varConsulta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(principalLayout.createSequentialGroup()
                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPlano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addComponent(varConsulta)
                        .addGap(18, 18, 18)
                        .addComponent(varExame)
                        .addGap(18, 18, 18)
                        .addComponent(varFatura)
                        .addGap(18, 18, 18)
                        .addComponent(varHistorico)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void varConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varConsultaActionPerformed
        String nmConsulta = JOptionPane.showInputDialog("nome da consulta");
        String valorConsulta = JOptionPane.showInputDialog("valor da consulta");

        if ("basico".equals(plano.getTipoPlano())) {
            plano.setTotalConsumido(plano.getTotalConsumido()
                    + Double.parseDouble(valorConsulta));
            plano.setHistorico(plano.getHistorico() + "Consulta: " + nmConsulta
                    + " valor: R$" + valorConsulta + "\n");

        } else if ("total".equals(plano.getTipoPlano())) {
            plano.setHistorico(plano.getHistorico() + "Consulta: " + nmConsulta
                    + " valor: R$" + valorConsulta + "\n");

        }
    }//GEN-LAST:event_varConsultaActionPerformed

    private void varExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varExameActionPerformed
        String nmExame = JOptionPane.showInputDialog("nome da consulta");
        String valorExame = JOptionPane.showInputDialog("valor da consulta");

        if ("basico".equals(plano.getTipoPlano())) {
            plano.setTotalConsumido(plano.getTotalConsumido()
                    + Double.parseDouble(valorExame));
            plano.setHistorico(plano.getHistorico() + "Exame: " + nmExame
                    + " valor: R$" + valorExame + "\n");

        } else if ("total".equals(plano.getTipoPlano())) {
            plano.setHistorico(plano.getHistorico() + "Exame: " + nmExame
                    + " valor: R$" + valorExame + "\n");

        }
    }//GEN-LAST:event_varExameActionPerformed

    private void varFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varFaturaActionPerformed
        mostrar.setText("Fatura \n" + String.valueOf(plano.getTotalConsumido()));
    }//GEN-LAST:event_varFaturaActionPerformed

    private void varHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varHistoricoActionPerformed
                mostrar.setText("Historico \n" +plano.getHistorico());

    }//GEN-LAST:event_varHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoPlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoPlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoPlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoPlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoPlano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPlano;
    private javax.swing.JTextArea mostrar;
    private javax.swing.JPanel principal;
    private javax.swing.JButton varConsulta;
    private javax.swing.JButton varExame;
    private javax.swing.JButton varFatura;
    private javax.swing.JButton varHistorico;
    // End of variables declaration//GEN-END:variables
}
